# Site settings
title: Cleavs
header-img: img/home-bg.png
email: cbrathwaite90@gmail.com
copyright_name: cleavs
description: > # this means to ignore newlines until "baseurl:"
  The rantings of an aspiring digital nomad
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  cleavs
learn_profile: cleavs
email_username: cbrathwaite90@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
